#!/usr/bin/env python3
import sqlite3
import json
import os
import shutil
import binascii
import sys
from datetime import datetime, timedelta

# Path to Chrome Cookies database
COOKIES_DB = "/workspaces/JaiziahGreene/Lil samson bro/Local/Google/Chrome/User Data/Default/Network/Cookies"

# Format suitable for cookie import extensions
def extract_cookies_for_import():
    # Create a copy of the database to avoid locks
    temp_db = "/tmp/temp_cookies_for_import.db"
    
    if not os.path.exists(COOKIES_DB):
        print(f"Error: Cookies database not found at {COOKIES_DB}")
        return []
    
    cookies_for_import = []
    
    try:
        # Copy the database
        shutil.copy2(COOKIES_DB, temp_db)
        
        # Connect to the copy
        conn = sqlite3.connect(temp_db)
        conn.row_factory = sqlite3.Row
        cursor = conn.cursor()
        
        # Query for cookies related to our target domains
        target_domains = [
            "sishrsb.ednet.ns.ca",
            "gnspes.ca",
            "everyone.ednet.ns.ca", 
            "saml.nspes.ca",
            ".ednet.ns.ca",
            ".nspes.ca",
            "ednet.ns.ca",
            "nspes.ca"
        ]
        
        for domain in target_domains:
            cursor.execute(
                "SELECT host_key, name, value, encrypted_value, path, expires_utc, is_secure, is_httponly, creation_utc, last_access_utc "
                "FROM cookies WHERE host_key LIKE ? OR host_key LIKE ?",
                (f'%{domain}%', f'%.{domain}%')
            )
            
            rows = cursor.fetchall()
            for row in cursor.fetchall():
                # Convert Chrome's timestamp format (microseconds since 1601-01-01)
                chrome_epoch = datetime(1601, 1, 1)
                
                # Calculate expiration date (if any)
                if row['expires_utc'] > 0:
                    expires_date = chrome_epoch + timedelta(microseconds=row['expires_utc'])
                    expires_timestamp = int((expires_date - datetime(1970, 1, 1)).total_seconds())
                else:
                    expires_timestamp = None
                
                # For Netscape cookie format
                cookie_for_import = {
                    "domain": row['host_key'],
                    "name": row['name'],
                    # We'll include both the value and hex of encrypted_value
                    "value": row['value'],
                    "encrypted_value_hex": binascii.hexlify(row['encrypted_value']).decode('utf-8'),
                    "path": row['path'],
                    "expires": expires_timestamp,
                    "secure": bool(row['is_secure']),
                    "httpOnly": bool(row['is_httponly'])
                }
                
                cookies_for_import.append(cookie_for_import)
        
        conn.close()
        os.remove(temp_db)
        
        return cookies_for_import
    
    except Exception as e:
        print(f"Error extracting cookies: {e}")
        try:
            conn.close()
        except:
            pass
        try:
            os.remove(temp_db)
        except:
            pass
        
        return []

# Create Netscape cookie format file (for cookie importers)
def write_netscape_cookies(cookies, output_file):
    with open(output_file, 'w') as f:
        f.write("# Netscape HTTP Cookie File\n")
        f.write("# https://curl.se/docs/http-cookies.html\n")
        f.write("# This file was generated by a script. Edit at your own risk.\n\n")
        
        for cookie in cookies:
            domain = cookie['domain']
            # Add the leading dot if missing (for Netscape format)
            if not domain.startswith('.') and not domain.startswith('#') and '.' in domain:
                domain_flag = "FALSE"
            else:
                domain_flag = "TRUE"
                
            # Netscape format:
            # domain_flag domain path secure expiry name value
            f.write(f"{cookie['domain']}\t{domain_flag}\t{cookie['path']}\t"
                   f"{'TRUE' if cookie['secure'] else 'FALSE'}\t"
                   f"{cookie['expires'] if cookie['expires'] else '0'}\t"
                   f"{cookie['name']}\t{cookie['value']}\n")
    
    print(f"Netscape format cookies written to {output_file}")

# Create JSON format for easy inspection
def write_json_cookies(cookies, output_file):
    with open(output_file, 'w') as f:
        json.dump(cookies, f, indent=2)
    
    print(f"JSON format cookies written to {output_file}")

# Export raw encrypted values for potential decryption
def write_encrypted_values(cookies, output_file):
    with open(output_file, 'w') as f:
        f.write("# Cookie name and encrypted values (hex) for potential decryption\n")
        f.write("# Format: domain,name,encrypted_value_hex\n\n")
        
        for cookie in cookies:
            f.write(f"{cookie['domain']},{cookie['name']},{cookie['encrypted_value_hex']}\n")
    
    print(f"Encrypted values written to {output_file}")

def main():
    cookies = extract_cookies_for_import()
    
    if cookies:
        print(f"Found {len(cookies)} cookies for educational domains")
        
        # Write cookies in different formats
        write_netscape_cookies(cookies, "/workspaces/JaiziahGreene/cookies_netscape.txt")
        write_json_cookies(cookies, "/workspaces/JaiziahGreene/cookies_json.txt")
        write_encrypted_values(cookies, "/workspaces/JaiziahGreene/cookies_encrypted.csv")
        
        print("\nCookie export complete. You can now:")
        print("1. Import cookies_netscape.txt into a browser using a cookie manager extension")
        print("2. Examine cookies_json.txt for cookie details")
        print("3. Use cookies_encrypted.csv if you want to attempt offline decryption")
    else:
        print("No cookies found for educational domains")

if __name__ == "__main__":
    main()
